server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
#  autoconfigure:
 #   exclude:
  #    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
   #   - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/users/**
        - id: booking-service-route
          uri: ${BOOKING_SERVICE_URL:http://booking-service:8082}
          predicates:
            - Path=/booking/**